# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5433/bis_db
spring.datasource.username=bis_user
spring.datasource.password=bis_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=WARN
logging.level.com.bis=INFO
